version: '3.5'

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=robot
    ports:
      - '5432:5432'
    volumes:
      - ./.config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.config/data:/var/lib/postgresql/data
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge
