version: "3.8"

services:
  api01: &api
    build: .
    hostname: api01
    environment:
      - ConnectionStrings__RobotDB=Server=sqldata,1433;Database=robot;User Id=sa;Password=Pass@word;TrustServerCertificate=true;
      - Jwt__Key=YcxjOMewdFfeZFQm5iGAYxTjR23Z93rLbyZucty3
      - Jwt__Issuer=https://robot-api
      - Jwt__Audience=https://robot-api
    depends_on:
      - sqldata
    networks:
      - robot-network
  
  api02:
    <<: *api
    hostname: api02
    
  nginx:
    image: nginx:latest
    volumes:
      - ./.config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - '9999:9999'
    networks:
      - robot-network
      
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    networks: 
      - robot-network
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
    driver: local
    
networks:
  robot-network:
    driver: bridge
